GET http://localhost:5000/task

###
POST  http://localhost:5000/task
Content-Type: application/json

{
    "task" : "test2",
    "completed" : "false"
}
###
PUT http://localhost:5000/task/61a8425d7948cc487abf0d59
Content-Type: application/json

{
    "task" : "test 3 updated",
    "completed" : "false"
}
###
DELETE http://localhost:5000/task/61a8425d7948cc487abf0d59